name:ci-cd pipeline
on:
push:
branches:[main]
workflow_dispathch:
jobs:
pipeline:
runs-on:ubuntu-latest
steps:
-uses:action/checkout@v4
-uses:action/setup-node@v4
-with:{node-version.18}
-run:npm install
-run:echo"build"
-runs:npm test
-runs:npm "deploy"
